### ISSUE TITLE
tests fail on 32bit machines

### ISSUE THREAD

**Issue by cleverca22** [ekmett/half#22]
from a 32bit machine:
```
λ> getHalf . toHalf . fromHalf . Half $ 31745
32257
```
from a 64bit machine:
```
λ> getHalf . toHalf . fromHalf . Half $ 31745
31745
```
other details, that both agree on:
```
λ> Half 31745
NaN
it :: Half
λ> Half 32257
NaN
31745 == 0x7c01
32257 == 0x7e01
```

the full test failures:
```
  test/Spec.hs:28:5:
  1) Round trip should round trip properly
       Falsifiable (after 60 tests and 5 shrinks):
         31745
         32257 /= 31745

  To rerun use: --match "/Round trip/should round trip properly/"

  test/Spec.hs:31:5:
  2) Round trip should round trip for a NaN value
       Falsifiable (after 1 test):
         32512 /= 32000

  To rerun use: --match "/Round trip/should round trip for a NaN value/"
```

and the changes to make quickcheck give better errors:
```
diff --git a/test/Spec.hs b/test/Spec.hs
index e4c59a7..f2b3806 100644
--- a/test/Spec.hs
+++ b/test/Spec.hs
@@ -23,10 +23,10 @@ main = hspec $ do
       or [a < b | a <- nans, b <- nans] `shouldBe` False

   describe "Round trip" $ do
-    let roundTrip w = (getHalf . toHalf . fromHalf . Half $ w) == w
+    let roundTrip w = (getHalf . toHalf . fromHalf . Half $ w) === w

     it "should round trip properly" $
       property roundTrip

     it "should round trip for a NaN value" $
-      roundTrip 0x7d00 `shouldBe` True
+      roundTrip 0x7d00
```

**Comment by ekmett** [comment]
I've had similar issues with `bytes` tests where NaNs don't round-trip in a similar fashion. I think I'm willing to simply redefine the problem away to say that we take NaNs to NaNs but not claim to preserve the exact NaN. That way lies madness and fighting the host execution environment.

**Comment by ekmett** [comment]
I've tweaked the tests to no longer claim idempotence holds for NaNs on the nose. 

GHC likes to fiddle with the signaling flag, IIRC. 

Can you try with `half` HEAD? If that looks good I can push out a 0.3.1.

**Comment by ekmett** [comment]
Closing as fixed. Please re-open if this is not the case.

**Comment by juhp** [comment]
I have applied the patches to the new Fedora package, thanks :+1:
