### ISSUE TITLE
Unexpected `read` behavior

### ISSUE THREAD

**Issue by dwincort** [ekmett/half#36]
I would expect `read "0x7C00" :: Half` to be the same as `POS_INF`, but it's not.  Instead, `getHalf $ read "0x7C00" == 30656` while `getHalf POS_INF == 31744`.  Likewise for other special values.

The same is true for `fromRational`, although I suppose I can understand an argument that `Half 0x7C00` should not equal `fromRational 0x7C00`.

**Comment by phadej** [comment]
```
*Numeric.Half> HALF_MAX
65504.0

*Numeric.Half> 0x7C00 :: Double
31744.0

*Numeric.Half> 0x7C00 :: Half
31744.0
```

This all looks correct to me. `read` for `Half` reads it as a number, not as binary representation.

**Comment by dwincort** [comment]
Oh okay.  I guess it was just unexpected to me.
